Found a JS Error when running the several JS fiddle code examples in safari.
Logs: TypeError: pc.addStream is not a function. (In 'pc.addStream(displayVideo(stream))', 'pc.addStream' is undefined)
Fixed js error when using safari due to deprecated RTCPeerConnection.addStream() method.

Updated js fiddle examples to use the addTrack() method instead.
https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/addStream